resource_group_name              = "tfrg-eus-001"
resource_group_location          = "East Europe"
virtual_network_name             = "tfvnet-eus-001"
subnet_name                      = "tfsnet-eus-001"
public_ip_name                   = "tfpip-eus-001"
network_interface_name           = "tfnic-eus-001"
azurerm_windows_virtual_machine  = "tfwinvm-2019"